apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: green
  template:
    metadata:
      labels:
        app: frontend
        version: green
    spec:
      containers:
        - name: frontend
          image: mexico.azurecr.io/jerney-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NGINX_PORT
              value: "8080"  